### ISSUE TITLE
issue of Synchronizing two cameras

### ISSUE THREAD

**Issue by Junes94** [iorodeo/bias#1]
Hi, I want to record the animal behavior by using two cameras (Flea3).
And I want them to start recording at the same time.
I want to use external trigger but it seems bias software still doesn't support external server mode.

Is there any way to solve my problem? or should I just use the Flycap2 ?

It would be pleasure if there's any help.
Best regards,
Junesu LEE

**Comment by iorodeo** [comment]
BIAS does support external  hardware trigger see the docs here http://public.iorodeo.com/notes/bias/basic_usage.html#trigger  Select the 'External' option to have the camera use an external hardware trigger.

**Comment by Junes94** [comment]
Thanks for your reply.
Yes, I saw that manual, but couldn't get it yet.
In flir support, they say that Flea3 camera has an input through GPIO pin 4, and GND for pin5.
So I connected those pins to my National Instrument USB digital I/O device, and triggered the camera.
However, the camera failed to get a video.

Should I need to do additional works ?
Thank you again,
JuneSu LEE
